# Generated by Django 5.0 on 2023-12-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('description', models.TextField(verbose_name='Описание Услуги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory', verbose_name='Название категории')),
            ],
        ),
    ]
