# Generated by Django 5.0 on 2023-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Описание Категории'),
        ),
    ]
