# Generated by Django 5.0 on 2023-12-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание Категории'),
        ),
    ]
